/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type Settings = {
  _id: string;
  _type: "settings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  password?: string;
};

export type Skill = {
  _id: string;
  _type: "skill";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  parent?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "skill";
  } | {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "category";
  };
};

export type Cv = {
  _id: string;
  _type: "cv";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  experience?: Array<{
    title?: string;
    employer?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "contact";
    };
    from?: string;
    to?: string;
    description?: string;
    _key: string;
  }>;
  education?: Array<{
    qualification?: string;
    institution?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "contact";
    };
    from?: string;
    to?: string;
    _key: string;
  }>;
  skills?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "category";
  }>;
};

export type Project = {
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  date?: string;
  categories?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "category";
  }>;
  skills?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "skill";
  }>;
  thumbnail?: {
    asset: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  description?: string;
  descriptionLong?: Markdown;
  content?: Array<{
    name?: string;
    span?: "half" | "full";
    content?: Array<{
      content?: Markdown;
      _type: "md";
      _key: string;
    } | {
      quote?: Markdown;
      attribution?: string;
      link?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "link";
      };
      _type: "quote";
      _key: string;
    } | {
      _key: string;
    } & Code | {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      caption?: string;
      _type: "image";
      _key: string;
    } | {
      main?: {
        asset: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        caption?: string;
        _type: "image";
      };
      alternative?: Array<{
        image?: {
          asset?: {
            _ref: string;
            _type: "reference";
            _weak?: boolean;
            [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
          };
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        };
        breakpoint?: "md" | "lg" | "xl" | "2xl";
        _key: string;
      }>;
      _type: "responsiveImage";
      _key: string;
    } | {
      file?: {
        asset: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
        };
        media?: unknown;
        _type: "file";
      };
      poster?: {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
      };
      alt?: string;
      ratio?: string;
      _type: "video";
      _key: string;
    } | {
      url?: string;
      poster?: {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
      };
      alt?: string;
      ratio?: string;
      caption?: string;
      _type: "remoteVideo";
      _key: string;
    }>;
    _type: "item";
    _key: string;
  }>;
  client?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "contact";
  };
  attributions?: Array<{
    name?: string;
    contacts?: Array<{
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      _key: string;
      [internalGroqTypeReferenceTo]?: "contact";
    }>;
    _type: "attribution";
    _key: string;
  }>;
  hideFromSearchEngines?: boolean;
  private?: boolean;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Markdown = string;

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Album = {
  _id: string;
  _type: "album";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  date?: string;
  location?: Geopoint;
  photos?: Array<{
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    caption?: string;
    location?: Geopoint;
    _type: "photo";
    _key: string;
  }>;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Contact = {
  _id: string;
  _type: "contact";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  type?: "company" | "individual" | "institution";
  link?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "link";
  };
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  description?: string;
};

export type Common = {
  _type: "common";
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    caption?: string;
    _type: "image";
  };
  decorativeImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  responsiveImage?: {
    main?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      caption?: string;
      _type: "image";
    };
    alternative?: Array<{
      image?: {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
      };
      breakpoint?: "md" | "lg" | "xl" | "2xl";
      _key: string;
    }>;
  };
  video?: {
    file?: {
      asset: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
      };
      media?: unknown;
      _type: "file";
    };
    poster?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    alt?: string;
    ratio?: string;
    caption?: string;
  };
  remoteVideo?: {
    url?: string;
    poster?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    alt?: string;
    ratio?: string;
    caption?: string;
  };
  markdown?: {
    content?: Markdown;
  };
  quote?: {
    quote?: Markdown;
    attribution?: string;
    link?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "link";
    };
  };
  code?: Code;
};

export type Code = {
  _type: "code";
  language?: string;
  filename?: string;
  code?: string;
  highlightedLines?: Array<number>;
};

export type Link = {
  _id: string;
  _type: "link";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  shortName?: string;
  url?: string;
};

export type GeopointRadius = {
  _type: "geopointRadius";
  lat?: number;
  lng?: number;
  alt?: number;
  radius?: number;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type AllSanitySchemaTypes = Settings | Skill | Cv | Project | SanityImageCrop | SanityImageHotspot | Markdown | Slug | Album | Geopoint | Contact | Category | Common | Code | Link | GeopointRadius | SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageMetadata | SanityFileAsset | SanityAssetSourceData | SanityImageAsset;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: lib/queries/resolve-dynamic.ts
// Variable: resolveDynamicQuery
// Query: {    'document': *[_id==$id][0]{        _id,  _type,  slug,  name,  title    },    'directRefs': *[references($id)] {        _id,  _type,  slug,  name,  title,    },    'indirectRefs': *[      $deep &&      references(        *[references($id)]._id      )    ] {        _id,  _type,  slug,  name,  title,    },  }
export type ResolveDynamicQueryResult = {
  document: {
    _id: string;
    _type: "album";
    slug: Slug | null;
    name: string | null;
    title: null;
  } | {
    _id: string;
    _type: "category";
    slug: Slug | null;
    name: string | null;
    title: null;
  } | {
    _id: string;
    _type: "contact";
    slug: null;
    name: string | null;
    title: null;
  } | {
    _id: string;
    _type: "cv";
    slug: null;
    name: null;
    title: null;
  } | {
    _id: string;
    _type: "link";
    slug: null;
    name: string | null;
    title: null;
  } | {
    _id: string;
    _type: "project";
    slug: Slug | null;
    name: string | null;
    title: null;
  } | {
    _id: string;
    _type: "sanity.fileAsset";
    slug: null;
    name: null;
    title: string | null;
  } | {
    _id: string;
    _type: "sanity.imageAsset";
    slug: null;
    name: null;
    title: string | null;
  } | {
    _id: string;
    _type: "settings";
    slug: null;
    name: null;
    title: null;
  } | {
    _id: string;
    _type: "skill";
    slug: null;
    name: string | null;
    title: null;
  } | null;
  directRefs: Array<{
    _id: string;
    _type: "album";
    slug: Slug | null;
    name: string | null;
    title: null;
  } | {
    _id: string;
    _type: "category";
    slug: Slug | null;
    name: string | null;
    title: null;
  } | {
    _id: string;
    _type: "contact";
    slug: null;
    name: string | null;
    title: null;
  } | {
    _id: string;
    _type: "cv";
    slug: null;
    name: null;
    title: null;
  } | {
    _id: string;
    _type: "link";
    slug: null;
    name: string | null;
    title: null;
  } | {
    _id: string;
    _type: "project";
    slug: Slug | null;
    name: string | null;
    title: null;
  } | {
    _id: string;
    _type: "sanity.fileAsset";
    slug: null;
    name: null;
    title: string | null;
  } | {
    _id: string;
    _type: "sanity.imageAsset";
    slug: null;
    name: null;
    title: string | null;
  } | {
    _id: string;
    _type: "settings";
    slug: null;
    name: null;
    title: null;
  } | {
    _id: string;
    _type: "skill";
    slug: null;
    name: string | null;
    title: null;
  }>;
  indirectRefs: Array<{
    _id: string;
    _type: "album";
    slug: Slug | null;
    name: string | null;
    title: null;
  } | {
    _id: string;
    _type: "category";
    slug: Slug | null;
    name: string | null;
    title: null;
  } | {
    _id: string;
    _type: "contact";
    slug: null;
    name: string | null;
    title: null;
  } | {
    _id: string;
    _type: "cv";
    slug: null;
    name: null;
    title: null;
  } | {
    _id: string;
    _type: "link";
    slug: null;
    name: string | null;
    title: null;
  } | {
    _id: string;
    _type: "project";
    slug: Slug | null;
    name: string | null;
    title: null;
  } | {
    _id: string;
    _type: "sanity.fileAsset";
    slug: null;
    name: null;
    title: string | null;
  } | {
    _id: string;
    _type: "sanity.imageAsset";
    slug: null;
    name: null;
    title: string | null;
  } | {
    _id: string;
    _type: "settings";
    slug: null;
    name: null;
    title: null;
  } | {
    _id: string;
    _type: "skill";
    slug: null;
    name: string | null;
    title: null;
  }>;
};

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    "\n  {\n    'document': *[_id==$id][0]{\n      \n  _id,\n  _type,\n  slug,\n  name,\n  title\n\n    },\n    'directRefs': *[references($id)] {\n      \n  _id,\n  _type,\n  slug,\n  name,\n  title\n,\n    },\n    'indirectRefs': *[\n      $deep &&\n      references(\n        *[references($id)]._id\n      )\n    ] {\n      \n  _id,\n  _type,\n  slug,\n  name,\n  title\n,\n    },\n  }\n": ResolveDynamicQueryResult;
  }
}
